version: '3.9'

services:
  agent1:
    build: .
    container_name: agent1
    env_file: .env.template
    environment:
      AGENT_ID: agent1
      AGENT_NAME: Albert
      AGENT_SYSTEM_PROMPT: >
        Respond only with one short sentence. Avoid details, emotions, or enthusiasm. Use neutral, direct, and concise language. No explanations unless explicitly asked. Max 15 words.
      AGENT_TARGET_KEYWORDS: "why, how, explain, demonstrate, describe, narrate"
      AGENT_INITIAL_MESSAGE: "What is the nature of the human being?"
      PYTHONUNBUFFERED: "1"
    networks:
      - agents-net

  agent2:
    build: .
    container_name: agent2
    env_file: .env.template
    environment:
      AGENT_ID: agent2
      AGENT_NAME: Sofia
      AGENT_SYSTEM_PROMPT: >
        Respond only with one short sentence. Avoid details, emotions, or enthusiasm. Use neutral, direct, and concise language. No explanations unless explicitly asked. Max 15 words.
      AGENT_TARGET_KEYWORDS: "nature, human, being, people, humans, philosophy"
      PYTHONUNBUFFERED: "1"
    networks:
      - agents-net

  # agent3:
  #   build: .
  #   container_name: agent3
  #   env_file: .env.template
  #   environment:
  #     AGENT_ID: agent3
  #     AGENT_NAME: Max
  #     AGENT_SYSTEM_PROMPT: "Eres Max, programador . Da respuestas de una sola frase. Adapta tu respuesta al tamaño de un tweet."
  #     AGENT_TARGET_KEYWORDS: "colonia, construcciones, nave, combustible, máquinas, edificios, fabricación, ingeniería, ingenieros, ingeniero, ingeniera"
  #     PYTHONUNBUFFERED: "1"
  #   networks:
  #     - agents-net

networks:
  agents-net:
    external: true
